<?php
/**
 * ContentUpdatePreview
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * The version of the OpenAPI document: 2024-03-20
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Plenty\AmazonPHP\SellingPartner\Model\FulfillmentInbound2024;

use \ArrayAccess;
use Plenty\AmazonPHP\SellingPartner\ObjectSerializer;

/**
 * ContentUpdatePreview Class Doc Comment
 *
 * @category Class
 * @description Preview of the changes that will be applied to the shipment.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class ContentUpdatePreview implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ContentUpdatePreview';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'content_update_preview_id' => 'string',
        'expiration' => 'string',
        'requested_updates' => '\Plenty\AmazonPHP\SellingPartner\Model\FulfillmentInbound2024\RequestedUpdates',
        'transportation_option' => '\Plenty\AmazonPHP\SellingPartner\Model\FulfillmentInbound2024\TransportationOption'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'content_update_preview_id' => null,
        'expiration' => null,
        'requested_updates' => null,
        'transportation_option' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'content_update_preview_id' => 'contentUpdatePreviewId',
        'expiration' => 'expiration',
        'requested_updates' => 'requestedUpdates',
        'transportation_option' => 'transportationOption'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'content_update_preview_id' => 'setContentUpdatePreviewId',
        'expiration' => 'setExpiration',
        'requested_updates' => 'setRequestedUpdates',
        'transportation_option' => 'setTransportationOption'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'content_update_preview_id' => 'getContentUpdatePreviewId',
        'expiration' => 'getExpiration',
        'requested_updates' => 'getRequestedUpdates',
        'transportation_option' => 'getTransportationOption'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['content_update_preview_id'] = $data['content_update_preview_id'] ?? null;
        $this->container['expiration'] = $data['expiration'] ?? null;
        $this->container['requested_updates'] = $data['requested_updates'] ?? null;
        $this->container['transportation_option'] = $data['transportation_option'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['content_update_preview_id'] === null) {
            $invalidProperties[] = "'content_update_preview_id' can't be null";
        }
        if ((mb_strlen($this->container['content_update_preview_id']) > 38)) {
            $invalidProperties[] = "invalid value for 'content_update_preview_id', the character length must be smaller than or equal to 38.";
        }

        if ((mb_strlen($this->container['content_update_preview_id']) < 38)) {
            $invalidProperties[] = "invalid value for 'content_update_preview_id', the character length must be bigger than or equal to 38.";
        }

        if (!preg_match("/^[a-zA-Z0-9-]*$/", $this->container['content_update_preview_id'])) {
            $invalidProperties[] = "invalid value for 'content_update_preview_id', must be conform to the pattern /^[a-zA-Z0-9-]*$/.";
        }

        if ($this->container['expiration'] === null) {
            $invalidProperties[] = "'expiration' can't be null";
        }
        if (!preg_match("/^([0-9]{4})-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/", $this->container['expiration'])) {
            $invalidProperties[] = "invalid value for 'expiration', must be conform to the pattern /^([0-9]{4})-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/.";
        }

        if ($this->container['requested_updates'] === null) {
            $invalidProperties[] = "'requested_updates' can't be null";
        }
        if ($this->container['transportation_option'] === null) {
            $invalidProperties[] = "'transportation_option' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets content_update_preview_id
     *
     * @return string
     */
    public function getContentUpdatePreviewId()
    {
        return $this->container['content_update_preview_id'];
    }

    /**
     * Sets content_update_preview_id
     *
     * @param string $content_update_preview_id Identifier of a content update preview.
     *
     * @return self
     */
    public function setContentUpdatePreviewId($content_update_preview_id)
    {
        if ((mb_strlen($content_update_preview_id) > 38)) {
            throw new \InvalidArgumentException(
                'invalid length for $content_update_preview_id when calling ContentUpdatePreview., must be smaller than or equal to 38.'
            );
        }
        if ((mb_strlen($content_update_preview_id) < 38)) {
            throw new \InvalidArgumentException(
                'invalid length for $content_update_preview_id when calling ContentUpdatePreview., must be bigger than or equal to 38.'
            );
        }
        if ((!preg_match("/^[a-zA-Z0-9-]*$/", $content_update_preview_id))) {
            throw new \InvalidArgumentException(
                "invalid value for $content_update_preview_id when calling ContentUpdatePreview., must conform to the pattern /^[a-zA-Z0-9-]*$/."
            );
        }

        $this->container['content_update_preview_id'] = $content_update_preview_id;

        return $this;
    }

    /**
     * Gets expiration
     *
     * @return string
     */
    public function getExpiration()
    {
        return $this->container['expiration'];
    }

    /**
     * Sets expiration
     *
     * @param string $expiration The date in ISO 8601 format for when the content update expires.
     *
     * @return self
     */
    public function setExpiration($expiration)
    {
        if ((!preg_match("/^([0-9]{4})-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/", $expiration))) {
            throw new \InvalidArgumentException(
                "invalid value for $expiration when calling ContentUpdatePreview., must conform to the pattern /^([0-9]{4})-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/."
            );
        }

        $this->container['expiration'] = $expiration;

        return $this;
    }

    /**
     * Gets requested_updates
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\FulfillmentInbound2024\RequestedUpdates
     */
    public function getRequestedUpdates()
    {
        return $this->container['requested_updates'];
    }

    /**
     * Sets requested_updates
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\FulfillmentInbound2024\RequestedUpdates $requested_updates requested_updates
     *
     * @return self
     */
    public function setRequestedUpdates($requested_updates)
    {
        $this->container['requested_updates'] = $requested_updates;

        return $this;
    }

    /**
     * Gets transportation_option
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\FulfillmentInbound2024\TransportationOption
     */
    public function getTransportationOption()
    {
        return $this->container['transportation_option'];
    }

    /**
     * Sets transportation_option
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\FulfillmentInbound2024\TransportationOption $transportation_option transportation_option
     *
     * @return self
     */
    public function setTransportationOption($transportation_option)
    {
        $this->container['transportation_option'] = $transportation_option;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed $value Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


