<?php
/**
 * PackingOption
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * The version of the OpenAPI document: 2024-03-20
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Plenty\AmazonPHP\SellingPartner\Model\FulfillmentInbound2024;

use \ArrayAccess;
use Plenty\AmazonPHP\SellingPartner\ObjectSerializer;

/**
 * PackingOption Class Doc Comment
 *
 * @category Class
 * @description A packing option contains a set of pack groups plus additional information about the packing option, such as any discounts or fees if it&#39;s selected.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class PackingOption implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PackingOption';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'discounts' => '\Plenty\AmazonPHP\SellingPartner\Model\FulfillmentInbound2024\Incentive[]',
        'expiration' => '\DateTime',
        'fees' => '\Plenty\AmazonPHP\SellingPartner\Model\FulfillmentInbound2024\Incentive[]',
        'packing_groups' => 'string[]',
        'packing_option_id' => 'string',
        'status' => 'string',
        'supported_shipping_configurations' => '\Plenty\AmazonPHP\SellingPartner\Model\FulfillmentInbound2024\ShippingConfiguration[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'discounts' => null,
        'expiration' => 'date-time',
        'fees' => null,
        'packing_groups' => null,
        'packing_option_id' => null,
        'status' => null,
        'supported_shipping_configurations' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'discounts' => 'discounts',
        'expiration' => 'expiration',
        'fees' => 'fees',
        'packing_groups' => 'packingGroups',
        'packing_option_id' => 'packingOptionId',
        'status' => 'status',
        'supported_shipping_configurations' => 'supportedShippingConfigurations'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'discounts' => 'setDiscounts',
        'expiration' => 'setExpiration',
        'fees' => 'setFees',
        'packing_groups' => 'setPackingGroups',
        'packing_option_id' => 'setPackingOptionId',
        'status' => 'setStatus',
        'supported_shipping_configurations' => 'setSupportedShippingConfigurations'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'discounts' => 'getDiscounts',
        'expiration' => 'getExpiration',
        'fees' => 'getFees',
        'packing_groups' => 'getPackingGroups',
        'packing_option_id' => 'getPackingOptionId',
        'status' => 'getStatus',
        'supported_shipping_configurations' => 'getSupportedShippingConfigurations'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['discounts'] = $data['discounts'] ?? null;
        $this->container['expiration'] = $data['expiration'] ?? null;
        $this->container['fees'] = $data['fees'] ?? null;
        $this->container['packing_groups'] = $data['packing_groups'] ?? null;
        $this->container['packing_option_id'] = $data['packing_option_id'] ?? null;
        $this->container['status'] = $data['status'] ?? null;
        $this->container['supported_shipping_configurations'] = $data['supported_shipping_configurations'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['discounts'] === null) {
            $invalidProperties[] = "'discounts' can't be null";
        }
        if ($this->container['fees'] === null) {
            $invalidProperties[] = "'fees' can't be null";
        }
        if ($this->container['packing_groups'] === null) {
            $invalidProperties[] = "'packing_groups' can't be null";
        }
        if ($this->container['packing_option_id'] === null) {
            $invalidProperties[] = "'packing_option_id' can't be null";
        }
        if ((mb_strlen($this->container['packing_option_id']) > 38)) {
            $invalidProperties[] = "invalid value for 'packing_option_id', the character length must be smaller than or equal to 38.";
        }

        if ((mb_strlen($this->container['packing_option_id']) < 38)) {
            $invalidProperties[] = "invalid value for 'packing_option_id', the character length must be bigger than or equal to 38.";
        }

        if (!preg_match("/^[a-zA-Z0-9-]*$/", $this->container['packing_option_id'])) {
            $invalidProperties[] = "invalid value for 'packing_option_id', must be conform to the pattern /^[a-zA-Z0-9-]*$/.";
        }

        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ((mb_strlen($this->container['status']) > 1024)) {
            $invalidProperties[] = "invalid value for 'status', the character length must be smaller than or equal to 1024.";
        }

        if ((mb_strlen($this->container['status']) < 1)) {
            $invalidProperties[] = "invalid value for 'status', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['supported_shipping_configurations'] === null) {
            $invalidProperties[] = "'supported_shipping_configurations' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets discounts
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\FulfillmentInbound2024\Incentive[]
     */
    public function getDiscounts()
    {
        return $this->container['discounts'];
    }

    /**
     * Sets discounts
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\FulfillmentInbound2024\Incentive[] $discounts Discount for the offered option.
     *
     * @return self
     */
    public function setDiscounts($discounts)
    {
        $this->container['discounts'] = $discounts;

        return $this;
    }

    /**
     * Gets expiration
     *
     * @return \DateTime|null
     */
    public function getExpiration()
    {
        return $this->container['expiration'];
    }

    /**
     * Sets expiration
     *
     * @param \DateTime|null $expiration The timestamp at which this packing option becomes no longer valid. This is based in ISO 8601 datetime with pattern `yyyy-MM-ddTHH:mm:ss.sssZ`.
     *
     * @return self
     */
    public function setExpiration($expiration)
    {
        $this->container['expiration'] = $expiration;

        return $this;
    }

    /**
     * Gets fees
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\FulfillmentInbound2024\Incentive[]
     */
    public function getFees()
    {
        return $this->container['fees'];
    }

    /**
     * Sets fees
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\FulfillmentInbound2024\Incentive[] $fees Fee for the offered option.
     *
     * @return self
     */
    public function setFees($fees)
    {
        $this->container['fees'] = $fees;

        return $this;
    }

    /**
     * Gets packing_groups
     *
     * @return string[]
     */
    public function getPackingGroups()
    {
        return $this->container['packing_groups'];
    }

    /**
     * Sets packing_groups
     *
     * @param string[] $packing_groups Packing group IDs.
     *
     * @return self
     */
    public function setPackingGroups($packing_groups)
    {
        $this->container['packing_groups'] = $packing_groups;

        return $this;
    }

    /**
     * Gets packing_option_id
     *
     * @return string
     */
    public function getPackingOptionId()
    {
        return $this->container['packing_option_id'];
    }

    /**
     * Sets packing_option_id
     *
     * @param string $packing_option_id Identifier of a packing option.
     *
     * @return self
     */
    public function setPackingOptionId($packing_option_id)
    {
        if ((mb_strlen($packing_option_id) > 38)) {
            throw new \InvalidArgumentException(
                'invalid length for $packing_option_id when calling PackingOption., must be smaller than or equal to 38.'
            );
        }
        if ((mb_strlen($packing_option_id) < 38)) {
            throw new \InvalidArgumentException(
                'invalid length for $packing_option_id when calling PackingOption., must be bigger than or equal to 38.'
            );
        }
        if ((!preg_match("/^[a-zA-Z0-9-]*$/", $packing_option_id))) {
            throw new \InvalidArgumentException(
                "invalid value for $packing_option_id when calling PackingOption., must conform to the pattern /^[a-zA-Z0-9-]*$/."
            );
        }

        $this->container['packing_option_id'] = $packing_option_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status The status of the packing option. Can be: `OFFERED`, `ACCEPTED`, or `EXPIRED`.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if ((mb_strlen($status) > 1024)) {
            throw new \InvalidArgumentException(
                'invalid length for $status when calling PackingOption., must be smaller than or equal to 1024.'
            );
        }
        if ((mb_strlen($status) < 1)) {
            throw new \InvalidArgumentException(
                'invalid length for $status when calling PackingOption., must be bigger than or equal to 1.'
            );
        }

        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets supported_shipping_configurations
     *
     * @return \Plenty\AmazonPHP\SellingPartner\Model\FulfillmentInbound2024\ShippingConfiguration[]
     */
    public function getSupportedShippingConfigurations()
    {
        return $this->container['supported_shipping_configurations'];
    }

    /**
     * Sets supported_shipping_configurations
     *
     * @param \Plenty\AmazonPHP\SellingPartner\Model\FulfillmentInbound2024\ShippingConfiguration[] $supported_shipping_configurations List of supported shipping modes.
     *
     * @return self
     */
    public function setSupportedShippingConfigurations($supported_shipping_configurations)
    {
        $this->container['supported_shipping_configurations'] = $supported_shipping_configurations;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed $value Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


