<?php

declare(strict_types=1);


namespace Plenty\AmazonPHP\SellingPartner\Model\FulfillmentInbound2024;

use Plenty\AmazonPHP\SellingPartner\ModelInterface;
use Plenty\AmazonPHP\SellingPartner\Exception\AssertionException;
use Plenty\AmazonPHP\SellingPartner\ObjectSerializer;

/**
* The Selling Partner API for FBA inbound operations.
*
* The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
*
* The version of the OpenAPI document: 2024-03-20
*
* This class was auto-generated by https://openapi-generator.tech
* Do not change it, it will be overwritten with next execution of /bin/generate.sh
 */
class PrepType
{
    /**
     * Possible values of this enum
     */
    const BLACK_SHRINKWRAP = 'ITEM_BLACK_SHRINKWRAP';

    const BLANKSTK = 'ITEM_BLANKSTK';

    const BOXING = 'ITEM_BOXING';

    const BUBBLEWRAP = 'ITEM_BUBBLEWRAP';

    const CAP_SEALING = 'ITEM_CAP_SEALING';

    const DEBUNDLE = 'ITEM_DEBUNDLE';

    const HANG_GARMENT = 'ITEM_HANG_GARMENT';

    const LABELING = 'ITEM_LABELING';

    const NO_PREP = 'ITEM_NO_PREP';

    const POLYBAGGING = 'ITEM_POLYBAGGING';

    const RMOVHANG = 'ITEM_RMOVHANG';

    const SETCREAT = 'ITEM_SETCREAT';

    const SETSTK = 'ITEM_SETSTK';

    const SIOC = 'ITEM_SIOC';

    const SUFFOSTK = 'ITEM_SUFFOSTK';

    const TAPING = 'ITEM_TAPING';

    private string $value;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BLACK_SHRINKWRAP,
            self::BLANKSTK,
            self::BOXING,
            self::BUBBLEWRAP,
            self::CAP_SEALING,
            self::DEBUNDLE,
            self::HANG_GARMENT,
            self::LABELING,
            self::NO_PREP,
            self::POLYBAGGING,
            self::RMOVHANG,
            self::SETCREAT,
            self::SETSTK,
            self::SIOC,
            self::SUFFOSTK,
            self::TAPING
        ];
    }

    public function __construct(string $value)
    {
        $this->value = $value;
    }

    public function toString(): string
    {
        return $this->value;
    }
}

